#!/bin/bash

#SBATCH --time=01:00:00
#SBATCH --partition=west
#SBATCH --nodes=2 --tasks-per-node=5
#SBATCH --error=COMMUNICATION_A_JA_2_10_200.err --output=COMMUNICATION_A_JA_2_10_200.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 10 ./partdiff-par 1 2 200 1 1 3.3504e-05
mpiexec -n 10 ./partdiff-par 1 2 200 1 1 3.3504e-05
mpiexec -n 10 ./partdiff-par 1 2 200 1 1 3.3504e-05
