#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=west
#SBATCH --nodes=1 --tasks-per-node=1
#SBATCH --error=WEAK_SCALING_JA_1_1_400.err --output=WEAK_SCALING_JA_1_1_400.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 1 ./partdiff-par 1 2 400 2 2 1000
mpiexec -n 1 ./partdiff-par 1 2 400 2 2 1000
mpiexec -n 1 ./partdiff-par 1 2 400 2 2 1000
