#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=west
#SBATCH --nodes=8 --tasks-per-node=8
#SBATCH --error=WEAK_SCALING_JA_8_64_3200.err --output=WEAK_SCALING_JA_8_64_3200.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 64 ./partdiff-par 1 2 3200 2 2 1000
mpiexec -n 64 ./partdiff-par 1 2 3200 2 2 1000
mpiexec -n 64 ./partdiff-par 1 2 3200 2 2 1000
