#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=west
#SBATCH --nodes=4 --tasks-per-node=4
#SBATCH --error=WEAK_SCALING_JA_4_16_1600.err --output=WEAK_SCALING_JA_4_16_1600.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 16 ./partdiff-par 1 2 1600 2 2 1000
mpiexec -n 16 ./partdiff-par 1 2 1600 2 2 1000
mpiexec -n 16 ./partdiff-par 1 2 1600 2 2 1000
